cd_test0/urls.py
from django.urls import path
from . import views
app_name='dofu_1'
urlpatterns=[
    path('song_list/',views.song_list,name='song_list'),
    path('upload_song/',views.upload_song,name='upload_song'),
    path('delete_song/<int:cd__test_id>/',views.delete_song,name='delete_song'),
    path('play/',views.play_back,name='play'),
]

music_site/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/',include('roll_cd.urls')),
    path('walk/',include('walk_cd.urls')),
    path('cd_test/',include('cd_test0.urls')),
    path('dofu_cd/',include('real_cd.urls')),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

real_cd/urls.py
from django.urls import path
from .views import upload_song,song_list,delete_song,play_back
app_name="dofu_cd"
urlpatterns=[
    path("upload_song/",upload_song,name="upload_song"),
    path("song_list/",song_list,name="song_list"),
    path("delete_song/<int:song_id>/",delete_song,name="delete_song"),
    path("play_back/<int:song_id>/",play_back,name="play_back"),
]

cd_test0/models.py
from django.db import models
import os
from django.dispatch import receiver
# Create your models here.
class Cd_test(models.Model):
    name=models.CharField(max_length=100)
    cd_file=models.FileField(upload_to='cd_file')
@receiver(models.signals.pre_delete,sender=Cd_test)
def delete_cd_file(sender,instance,**kwargs):
    if instance.cd_file:
        if os.path.isfile(instance.cd_file.path):
            os.remove(instance.cd_file.path)

cd_test0/forms.py
from django import forms
from .models import Cd_test
class SongForm(forms.ModelForm):
    class Meta:
        model=Cd_test
        fields=['name','cd_file']

cd_test0/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Cd_test
from .forms import SongForm
# Create your views here.
def song_list(request):
    songs=Cd_test.objects.all()
    return render(request,'cd_test0/song_list.html',{'songs':songs})
def upload_song(request):
    if request.method=='POST':
        form=SongForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('dofu_1:song_list')
    else:
        form=SongForm()
    return render(request,'cd_test0/upload_song.html',{'form':form})
def delete_song(request,cd__test_id):
    song=get_object_or_404(Cd_test,pk=cd__test_id)
    if request.method=='POST':
        song.delete()
        return redirect('dofu_1:song_list')
    return render(request,'cd_test0/delete_song.html',{'song':song})
def play_back(request):
    song_list=Cd_test.objects.all()
    return render(request,'cd_test0/play.html',{'song_list':song_list})

cd_test0/templates/cd_test0/delete_song.html
<!DOCTYPE html>
<html>
<body>
	<h1>Delete Song</h1>
	<p>delete "{{ song.name }}"</p>
	<form method="post">
		{% csrf_token %}
		<input type="submit" value="Delete">
	</form>
</body>
</html>

cd_test0/templates/cd_test0/play.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<style>
		body{
			margin:0;
			padding: 0;
			height: 100vh;
			display: flex;
			justify-content: center;
			align-items: center;
			background-image: url("{% static 'images/kid.jpg' %}");
			background-size: cover;
			background-repeat: no-repeat;
			background-position: center;
			background-attachment: fixed;
			backdrop-filter: blur(5px);
		}
		#playButton:hover{
			cursor: pointer;
		}
		@keyframes rotate {
			from{
				transform: rotate(0deg);
			}
			to{
				transform: rotate(360deg);
			}
		}
		#playButton.rotate {
			animation: rotate 5s linear infinite;
		}
		.dropdown{
			position: fixed;
			top: 0;
			left: 0;
			display: inline-block;
		}
		.dropdown-content{
			display: none;
			position: absolute;
			background-color: #f9f9f9;
			min-width: 150px;
			box-shadow: 0px 8px 16px 0px rgba(0,0,0,2);
			z-index: 1;
		}
		.dropdown-content a {
			color: black;
			padding: 12px 16px;
			text-decoration: none;
			display: block;
		}
		.dropdown-content a:hover {
			background-color: #f1f1f1;
		}
		.progress-bar-container{
			position: fixed;
			bottom: 0;
			left: 0;
			width: 100%;
			height: 30px;
			overflow: hidden;
		}
		.progress-gif{
			position: absolute;
			height: 100%;
		}
		.dagou{
			position: absolute;
			height: 100%;
		}

	</style>
</head>
<body>
	<div class='dropdown'>
		<button onclick='toggleDropdown()'>Menu</button>
		<div id='menu' class='dropdown-content'>
			<a href="{% url 'dofu_1:song_list' %}" target="_blank">Song_list</a>
			<a href="{% url 'dofu_1:upload_song' %}" target="_blank">Upload_song</a>
		</div>
	</div>
	<div class="progress-bar-container">
		<img class="progress-gif" src="{% static 'images/xiaogou_0.gif' %}">
		<img class="dagou" src="{% static 'images/dagou_0.gif' %}" hidden>
	</div>
	
	<img id='playButton' src="{% static 'images/cd_5.jpg' %}" alt="Play Button">
	<audio id='music' controls style="display: none;">
		{% for song in song_list %}
			<source src="{{ song.cd_file.url }}" type="audio/mpeg">
		{% endfor %}
	</audio>
	<script>
		const albumCover = document.getElementById('playButton');
        const audioPlayer = document.getElementById('music');
        const audioNumber=document.getElementsByTagName('source')
        let currentSong=0;
        albumCover.addEventListener('click', () => {
            if (audioPlayer.paused) {
                audioPlayer.play();
            } else {
                audioPlayer.pause();
            }
        });

        audioPlayer.addEventListener('play',()=>{
        	albumCover.classList.add('rotate');
        });
        audioPlayer.addEventListener('pause',()=>{
        	albumCover.classList.remove('rotate');
        });
        audioPlayer.addEventListener('ended',()=>{
        	currentSong++;
        	if(currentSong>=audioNumber.length){
        		currentSong=0;
        	}
        	audioPlayer.src=audioNumber[currentSong].src;
        	audioPlayer.play();
        });
        function toggleDropdown(){
        	var dropdownMenu=document.getElementById('menu');
        	if(dropdownMenu.style.display==="block"){
        		dropdownMenu.style.display="none";
        	}else{
        		dropdownMenu.style.display="block";
        	}
        }
        window.onclick=function(event) {
        	if(!event.target.matches('.dropdown button')){
        		var dropdownMenus=document.getElementsByClassName("dropdown-content");
        		for(var i=0;i<dropdownMenus.length;i++){
        			var openDropdownMenu=dropdownMenus[i];
        			if(openDropdownMenu.style.display==="block"){
        				openDropdownMenu.style.display="none";
        			}
        		}
        	}
        }
        document.addEventListener("keydown",function(event){
        	if(event.key === "ArrowLeft"){
        		currentSong--;
        		if(currentSong<=0){
        			currentSong=0;
        		}
        		audioPlayer.src=audioNumber[currentSong].src;
        		audioPlayer.play();
        		console.log('change last song');
        	}else if(event.key === "ArrowRight"){
        		currentSong++;
        		if(currentSong>=audioNumber.length){
        			currentSong=0;
        		}
        		audioPlayer.src=audioNumber[currentSong].src;
        		audioPlayer.play();
        		console.log("change next song");
        	}
        	if(event.key === " "){
        		if(audioPlayer.paused){
        			audioPlayer.play();
        		}else {
        			audioPlayer.pause();
        		}
        	}
        });
        function updateProgressBar(){
        	var gif=document.querySelector(".progress-gif");
        	var dagou=document.querySelector(".dagou");
        	var progress=(audioPlayer.currentTime / audioPlayer.duration)*100;
        	gif.style.left=progress+"%";
        	dagou.style.left=(progress-10)+"%";
        	if(progress >= 10){
        		dagou.removeAttribute("hidden");
        	}else{
        		dagou.setAttribute("hidden","hidden");
        	}
        }
        audioPlayer.addEventListener("timeupdate",function(){
        	updateProgressBar();
        });
	</script>
</body>
</html>

cd_test0/templates/cd_test0/song_list.html
<!DOCTYPE html>
<html>
<body>
	<h1>Song List</h1>
	<ul>
		{% for song in songs %}
			<li>
				{{ song.name }}
				<a href="{% url 'dofu_1:delete_song' song.id %}">Delete</a>
			</li>
		{% endfor %}
	</ul>
	 <a href="{% url 'dofu_1:upload_song' %}">Upload Song</a>
</body>
</html>

cd_test0/templates/cd_test0/upload_song.html
<!DOCTYPE html>
<html>
<body>
	<h1>Upload Song</h1>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<button type='submit'>Upload</button>
	</form>
</body>
</html>