music_site/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/',include('roll_cd.urls')),
    path('walk/',include('walk_cd.urls')),
    path('cd_test/',include('cd_test0.urls')),
    path('dofu_cd/',include('real_cd.urls')),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

real_cd/urls.py
from django.urls import path
from .views import upload_song,song_list,delete_song,play_back
app_name="dofu_cd"
urlpatterns=[
    path("upload_song/",upload_song,name="upload_song"),
    path("song_list/",song_list,name="song_list"),
    path("delete_song/<int:song_id>/",delete_song,name="delete_song"),
    path("play_back/<int:song_id>/",play_back,name="play_back"),
]

real_cd/models.py
from django.db import models
import os
from django.dispatch import receiver
# Create your models here.
class Song(models.Model):
    name=models.CharField(max_length=100,unique=True)
    audio_file=models.FileField(upload_to="dofu_file/")
@receiver(models.signals.pre_delete,sender=Song)
def delete_audio_file(sender,instance,**kwargs):
    if instance.audio_file:
        if os.path.isfile(instance.audio_file.path):
            os.remove(instance.audio_file.path)
class Lyric(models.Model):
    song=models.ForeignKey(Song,on_delete=models.CASCADE)
    text=models.TextField()
    lyr_file=models.FileField(upload_to="cd_lyr/")

    

real_cd/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Song,Lyric
from django.template.defaultfilters import escape
from django.db.models import Max
# Create your views here.
def upload_song(request):
    if request.method=="POST":
        name=request.POST["name"]
        audio_file=request.FILES["audio_file"]
        lyr_file=request.FILES["lyr_file"]
        song=Song.objects.create(name=name,audio_file=audio_file)
        lyrics=lyr_file.read().decode('utf-8')
        lyric_lines=lyrics.splitlines()
        for line in lyric_lines:
            Lyric.objects.create(song=song,text=line)
        return redirect("dofu_cd:song_list")
    return render(request,"real_cd/upload_song.html")
def song_list(request):
    songs=Song.objects.all()
    return render(request,"real_cd/song_list.html",{"songs":songs})
def delete_song(request,song_id):
    song=get_object_or_404(Song,pk=song_id)
    if request.method=="POST":
        song.delete()
        return redirect("dofu_cd:song_list")
    return render(request,"real_cd/delete_song.html",{"song":song})
def play_back(request,song_id):
    max_song_id = Song.objects.all().order_by('-id').first().id
    song=Song.objects.get(pk=song_id)
    lyrics=Lyric.objects.filter(song=song)
    lyric_text='\n'.join(f"{escape(lyric.text)}" for lyric in lyrics)
    return render(request,"real_cd/play_back.html",{"song":song,"lyrics":lyric_text,"max_id":max_song_id})

real_cd/templates/real_cd/delete_song.html
<!DOCTYPE html>
<html>
<body>
	<h1>Delete {{ song.name }}</h1>
	<form method="post">
		{% csrf_token %}
		<input type="submit" value="Delete">
	</form>
</body>
</html>

real_cd/templates/real_cd/play_back.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<style>
		body{
			margin: 0;
			padding: 0;
			height: 100vh;
			display: flex;
			justify-content: center;
			align-items: center;
			background-image: url("{% static 'images/benghuai.gif' %}");
			background-size: cover;
			background-repeat: no-repeat;
			background-position: center;
			background-attachment: fixed;
		}
		#playButton{
			position: fixed;
		}
		#playButton:hover{
			cursor: pointer;
		}
		@keyframes rotate{
			from{
				transform: rotate(0deg);
			}
			to{
				transform: rotate(360deg);
			}
		}
		#playButton.rotate{
			animation: rotate 5s linear infinite;
		}
		.progress-bar-container{
			position: fixed;
			bottom: 0;
			left: 0;
			width: 100%;
			height: 30px;
			overflow: hidden;
		}
		.xiaogou{
			position: absolute;
			height: 100%;
		}
		.dagou{
			position: absolute;
			height: 100%;
		}
		#lyrics{
			position: fixed;
			white-space: pre-wrap;
			text-align: center;
			font-size: 24px;
			line-height: 1.6;
			display: none;
			left: 0;
			right: 0;
			bottom: 40px;
			color: white;
		}
		#youling{
			position: fixed;
			height: 15%;
			left: 0;
			bottom: 40px;

		}
		#youling:hover{
			cursor: pointer;
		}
		.dropdown-menu{
			position: fixed;
			top: 0;
			left: 0;
			display: inline-block;
			background-color: transparent;
		}
		.menu-content{
			display: none;
			position: absolute;
			background-color: transparent;
			min-width: 100px;
			box-shadow: 0px 8px 16px 0px rgba(0,0,0,2);
			z-index: 1;
		}
		.menu-content a{
			color: black;
			padding: 12px 16px;
			text-decoration: none;
			display: block;
		}
		.menu-content a:hover{
			background-color: #f1f1f1;
		}
		#rainBox{
			position: fixed;
			width: 100vw;
			height: 100vh;
			top: 0;
			left: 0;
			pointer-events: none;
		}
		.rain{
			position: absolute;
			width: 2px;
			height: 50px;
			background: linear-gradient(rgba(255,255,255,0.3),rgba(255,255,255,0.6));
		}

	</style>
</head>
<body>
	<input type="hidden" id="currentSongId" value="{{ song.id }}">
	<div id="rainBox">
	</div>
	<div class='dropdown-menu'>
		<button style="background-color: transparent;color: #808080;" onclick='toggleDropdown()'>DOFU</button>
		<div id='menu' class='menu-content'>
			<a href="{% url 'dofu_cd:song_list' %}" target="_blank">List</a>
			<a href="{% url 'dofu_cd:upload_song' %}" target="_blank">Upload</a>
		</div>
	</div>

	<img id="playButton" src="{% static 'images/dofu_cd.jpg' %}" alt="PlayButton">
	<audio id="music">
		<source src="{{ song.audio_file.url }}" type="audio/mpeg">
	</audio>
	<img id="youling" src="{% static 'images/youling_0.gif' %}">
	<div id="lyrics">
	</div>
	<div class="progress-bar-container">
		<img class="xiaogou" src="{% static 'images/xiaogou_0.gif' %}">
		<img class="dagou" src="{% static 'images/dagou_0.gif' %}" hidden>
	</div>
	<script>
		const play_button=document.getElementById('playButton');
		const audioPlayer=document.getElementById('music');
		const lyricsDiv=document.getElementById('lyrics');
		const songId=document.getElementById('currentSongId');
		const maxid={{ max_id }};
		const youling=document.getElementById('youling');
		const box=document.getElementById('rainBox');
		let lyrics=`{{ lyrics|safe }}`.split('\n');
		let timestamps=[];
		let isRaining=false;
		let boxWidth=box.clientWidth;
		let boxHeight=box.clientHeight;
		let isRaing=false;
		let rainInterval;
		window.onresize=function(){
			boxWidth=box.clientWidth;
			boxHeight=box.clientHeight;
		}
		function toggleRain(){
			if(isRaining){
				clearInterval(rainInterval);
				rainInterval=null;
				isRaining=false;
			}else{
				rainInterval=setInterval(()=>{
					const rain=document.createElement('div');
					rain.classList.add('rain');
					rain.style.top=0;
					rain.style.left=Math.random()*boxWidth+'px';
					rain.style.opacity=Math.random();
					box.appendChild(rain);
					let race=1;
					const timer=setInterval(()=>{
						if(parseInt(rain.style.top)>boxHeight){
							clearInterval(timer);
							box.removeChild(rain);
						}
						race++;
						rain.style.top=parseInt(rain.style.top)+race+'px';
					},20);
				},50);
				isRaining=true;
			}	
		}
		youling.addEventListener('click',toggleRain);

		for(let i=0; i<lyrics.length; i++){
			const line=lyrics[i];
			const matches=line.match(/\[(\d+:\d+\.\d+)\]/);
			if(matches){
				const timestamp=matches[1];
				timestamps.push({
					time: convertTimestampToSecond(timestamp),
					text: line.replace(matches[0],'').trim()
				});
			}
		}
		function convertTimestampToSecond(timestamp){
			const timeParts=timestamp.split(':');
			const minutes=parseInt(timeParts[0]);
			const seconds=parseFloat(timeParts[1]);
			return minutes*60+seconds;
		}
		function displayLyrics(currentTime){
			for(let i=0; i<timestamps.length; i++){
				if(i===timestamps.length-1 || currentTime<timestamps[i+1].time){
					lyricsDiv.innerText=timestamps[i].text;
					break;
				}
			}
		}
		audioPlayer.addEventListener('timeupdate',function(){
			displayLyrics(audioPlayer.currentTime);
		});
		audioPlayer.addEventListener('play',function(){
			lyricsDiv.style.display='block';
		});

		play_button.addEventListener('click',()=>{
			if(audioPlayer.paused){
				audioPlayer.play();
			}else {
				audioPlayer.pause();
			}
		});
		audioPlayer.addEventListener('play',()=>{
			play_button.classList.add('rotate');
		});
		audioPlayer.addEventListener('pause',()=>{
			play_button.classList.remove('rotate');
		});
        function updateProgressBar(){
        	var xiaogou=document.querySelector(".xiaogou");
        	var dagou=document.querySelector(".dagou");
        	var progress=(audioPlayer.currentTime / audioPlayer.duration)*100;
        	xiaogou.style.left=progress+"%";
        	dagou.style.left=(progress-10)+"%";
        	if(progress>10){
        		dagou.removeAttribute("hidden");
        	}else{
        		dagou.setAttribute("hidden","hidden");
        	}
        }
        audioPlayer.addEventListener('timeupdate',function(){
        	updateProgressBar();
        });
        audioPlayer.addEventListener('ended',function(){
        	let songid=parseInt(songId.value);
        	songid++;
        	if(songid>maxid){
        		songid=4;
        	}
        	songId.value=songid;
        	let newUrl=window.location.href.replace(/\/(\d+)\//,`/${songid}/`);
        	window.location.href=newUrl;
        });
        document.addEventListener('keydown',function(event){
        	if(event.key==="ArrowLeft"){
        	let songid=parseInt(songId.value);
        	songid--;
        	if(songid<=4){
        		songid=4;
        	}
        	songId.value=songid;
        	let newUrl=window.location.href.replace(/\/(\d+)\//,`/${songid}/`);
        	window.location.href=newUrl;
        	}else if(event.key==="ArrowRight"){
        	let songid=parseInt(songId.value);
        	songid++;
        	if(songid>maxid){
        		songid=4;
        	}
        	songId.value=songid;
        	let newUrl=window.location.href.replace(/\/(\d+)\//,`/${songid}/`);
        	window.location.href=newUrl;
        	}else if(event.key===" "){
        		if(audioPlayer.paused){
        			audioPlayer.play();
        		}else{
        			audioPlayer.pause();
        		}
        	}
        });
        window.onload=()=>{
        	audioPlayer.play();
        };
        function toggleDropdown(){
        	var dropdownMenu=document.getElementById('menu');
        	if(dropdownMenu.style.display==="block"){
        		dropdownMenu.style.display="none";
        	}
        	else{
        		dropdownMenu.style.display="block";
        	}
        }
        window.onclick=function(event){
        	if(!event.target.matches('.dropdown-menu button')){
        		var dropdownMenus=document.getElementsByClassName("menu-content");
        		for(var i=0; i<dropdownMenus.length; i++){
        			var openMenu=dropdownMenus[i];
        			if(openMenu.style.display==="block"){
        				openMenu.style.display="none";
        			}
        		}
        	}
        }
    </script>
</body>
</html>

real_cd/templates/real_cd/song_list.html
<!DOCTYPE html>
<html>
<body>
	<ul>
		{% for song in songs %}
		<li>
			{{ song.name }}
			<a href="{% url 'dofu_cd:delete_song' song_id=song.id %}">Delete</a>
		</li>
		{% endfor %}
	</ul>
	<a href="{% url 'dofu_cd:upload_song' %}">Upload_song</a>
</body>
</html>

real_cd/templates/real_cd/upload_song.html
<!DOCTYPE html>
<html>
<body>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<label for="name">Name:</label>
		<input type="text" id="name" name="name"><br>
		<label for="audio_file">Audio_file:</label>
		<input type="file" id="audio_file" name="audio_file"><br>
		<label for="lyr_file">Lyric_file:</label>
		<input type="file" id="lyr_file" name="lyr_file"><br>
		<input type="submit" value="Upload">		
	</form>
	
</body>
</html>